import type { Indicator } from "@/types";

export const indicators: Indicator[] = [
  // ─── United States ─────────────────────────────────────────────────────────
  {
    id: "gdp",
    name: "GDP",
    source: "fred",
    seriesId: "GDP",
    unit: "Billions of Dollars",
    category: "nationalAccounts",
    description: "Gross Domestic Product",
    categoryType: "country",
    country: "US",
  },
  {
    id: "unemployment",
    name: "Unemployment Rate",
    source: "fred",
    seriesId: "UNRATE",
    unit: "Percent",
    category: "labor",
    description: "Civilian Unemployment Rate",
    categoryType: "country",
    country: "US",
  },
  {
    id: "cpi",
    name: "CPI",
    source: "fred",
    seriesId: "CPIAUCSL",
    unit: "Index 1982-1984=100",
    category: "prices",
    description: "Consumer Price Index for All Urban Consumers",
    categoryType: "country",
    country: "US",
  },
  {
    id: "fed_funds_rate",
    name: "Federal Funds Rate",
    source: "fred",
    seriesId: "FEDFUNDS",
    unit: "Percent",
    category: "interestRates",
    description: "Federal Funds Effective Rate",
    categoryType: "country",
    country: "US",
  },
  {
    id: "treasury_10y",
    name: "10-Year Treasury Rate",
    source: "fred",
    seriesId: "DGS10",
    unit: "Percent",
    category: "interestRates",
    description:
      "Market Yield on U.S. Treasury Securities at 10-Year Constant Maturity",
    categoryType: "country",
    country: "US",
  },
  {
    id: "sp500",
    name: "S&P 500",
    source: "fred",
    seriesId: "SP500",
    unit: "Index",
    category: "stockMarket",
    description: "S&P 500 Index",
    categoryType: "country",
    country: "US",
  },
  {
    id: "industrial_production",
    name: "Industrial Production",
    source: "fred",
    seriesId: "INDPRO",
    unit: "Index 2017=100",
    category: "production",
    description: "Industrial Production: Total Index",
    categoryType: "country",
    country: "US",
  },
  {
    id: "housing_starts",
    name: "Housing Starts",
    source: "fred",
    seriesId: "HOUST",
    unit: "Thousands of Units",
    category: "housing",
    description: "New Privately-Owned Housing Units Started",
    categoryType: "country",
    country: "US",
  },
  {
    id: "consumer_sentiment",
    name: "Consumer Sentiment",
    source: "fred",
    seriesId: "UMCSENT",
    unit: "Index 1966Q1=100",
    category: "sentiment",
    description: "University of Michigan: Consumer Sentiment",
    categoryType: "country",
    country: "US",
  },
  {
    id: "pce",
    name: "PCE",
    source: "fred",
    seriesId: "PCE",
    unit: "Billions of Dollars",
    category: "nationalAccounts",
    description: "Personal Consumption Expenditures",
    categoryType: "country",
    country: "US",
  },
  {
    id: "trade_balance",
    name: "Trade Balance",
    source: "fred",
    seriesId: "BOPGSTB",
    unit: "Millions of Dollars",
    category: "trade",
    description:
      "Trade Balance: Goods and Services, Balance of Payments Basis",
    categoryType: "country",
    country: "US",
  },
  {
    id: "retail_sales",
    name: "Retail Sales",
    source: "fred",
    seriesId: "RSAFS",
    unit: "Millions of Dollars",
    category: "consumption",
    description: "Advance Retail Sales: Retail Trade",
    categoryType: "country",
    country: "US",
  },

  // ─── Euro Area ─────────────────────────────────────────────────────────────
  {
    id: "eu_gdp",
    name: "GDP",
    source: "fred",
    seriesId: "CLVMNACSCAB1GQEA19",
    unit: "Millions of Chained 2010 Euros",
    category: "nationalAccounts",
    description: "Real Gross Domestic Product for Euro Area (19 Countries)",
    categoryType: "country",
    country: "EuroArea",
  },
  {
    id: "eu_unemployment",
    name: "Unemployment Rate",
    source: "fred",
    seriesId: "LRHUTTTTEZM156S",
    unit: "Percent",
    category: "labor",
    description:
      "Harmonised Unemployment Rate: Total: All Persons for Euro Area",
    categoryType: "country",
    country: "EuroArea",
  },
  {
    id: "eu_hicp",
    name: "HICP",
    source: "fred",
    seriesId: "CP0000EZ19M086NEST",
    unit: "Index 2025=100",
    category: "prices",
    description:
      "Harmonized Index of Consumer Prices: Total for Euro Area (19 Countries)",
    categoryType: "country",
    country: "EuroArea",
  },
  {
    id: "eu_ecb_rate",
    name: "ECB Main Refinancing Rate",
    source: "fred",
    seriesId: "ECBMRRFR",
    unit: "Percent",
    category: "interestRates",
    description:
      "ECB Main Refinancing Operations Rate: Fixed Rate Tenders for Euro Area",
    categoryType: "country",
    country: "EuroArea",
  },

  // ─── Japan ─────────────────────────────────────────────────────────────────
  {
    id: "jp_gdp",
    name: "GDP",
    source: "fred",
    seriesId: "JPNRGDPEXP",
    unit: "Billions of Chained 2015 Yen",
    category: "nationalAccounts",
    description: "Real Gross Domestic Product for Japan",
    categoryType: "country",
    country: "Japan",
  },
  {
    id: "jp_unemployment",
    name: "Unemployment Rate",
    source: "fred",
    seriesId: "LRHUTTTTJPM156S",
    unit: "Percent",
    category: "labor",
    description:
      "Infra-Annual Labor Statistics: Monthly Unemployment Rate Total for Japan",
    categoryType: "country",
    country: "Japan",
  },
  {
    id: "jp_cpi",
    name: "CPI",
    source: "fred",
    seriesId: "CPALTT01JPM659N",
    unit: "Index 2015=100",
    category: "prices",
    description: "Consumer Price Indices: Total for Japan",
    categoryType: "country",
    country: "Japan",
  },
  {
    id: "jp_boj_rate",
    name: "BOJ Policy Rate",
    source: "fred",
    seriesId: "IRSTCI01JPM156N",
    unit: "Percent",
    category: "interestRates",
    description: "Call Money/Interbank Rate for Japan",
    categoryType: "country",
    country: "Japan",
  },

  // ─── China ─────────────────────────────────────────────────────────────────
  {
    id: "cn_gdp",
    name: "GDP",
    source: "fred",
    seriesId: "MKTGDPCNA646NWDB",
    unit: "Current US Dollars",
    category: "nationalAccounts",
    description: "Gross Domestic Product for China",
    categoryType: "country",
    country: "China",
  },
  {
    id: "cn_cpi",
    name: "CPI",
    source: "fred",
    seriesId: "CPALTT01CNM659N",
    unit: "Index 2015=100",
    category: "prices",
    description: "Consumer Price Indices: Total for China",
    categoryType: "country",
    country: "China",
  },
  {
    id: "cn_interest_rate",
    name: "Interest Rate",
    source: "fred",
    seriesId: "INTDSRCNM193N",
    unit: "Percent per Annum",
    category: "interestRates",
    description: "Interest Rates, Discount Rate for China",
    categoryType: "country",
    country: "China",
  },

  // ─── United Kingdom ────────────────────────────────────────────────────────
  {
    id: "uk_gdp",
    name: "GDP",
    source: "fred",
    seriesId: "UKNGDP",
    unit: "Millions of Pounds",
    category: "nationalAccounts",
    description: "Gross Domestic Product for United Kingdom",
    categoryType: "country",
    country: "UK",
  },
  {
    id: "uk_unemployment",
    name: "Unemployment Rate",
    source: "fred",
    seriesId: "LRHUTTTTGBM156S",
    unit: "Percent",
    category: "labor",
    description:
      "Infra-Annual Labor Statistics: Monthly Unemployment Rate Total for United Kingdom",
    categoryType: "country",
    country: "UK",
  },
  {
    id: "uk_cpi",
    name: "CPI",
    source: "fred",
    seriesId: "GBRCPIALLMINMEI",
    unit: "Index 2015=100",
    category: "prices",
    description: "Consumer Price Indices: CPI Total for United Kingdom",
    categoryType: "country",
    country: "UK",
  },
  {
    id: "uk_boe_rate",
    name: "BOE Bank Rate",
    source: "fred",
    seriesId: "BOERUKM",
    unit: "Percent per Annum",
    category: "interestRates",
    description: "Bank of England Policy Rate",
    categoryType: "country",
    country: "UK",
  },

  // ─── Global / Commodities ──────────────────────────────────────────────────
  {
    id: "oil_wti",
    name: "WTI Crude Oil",
    source: "dbnomics",
    datasetCode: "WFIVERDB-5",
    providerCode: "FRED",
    unit: "Dollars per Barrel",
    category: "commodities",
    description: "Crude Oil WTI - Daily",
    categoryType: "global",
  },
  {
    id: "gold_price",
    name: "Gold Price",
    source: "dbnomics",
    datasetCode: "GFDEGDQ188S",
    providerCode: "FRED",
    unit: "US Dollars",
    category: "commodities",
    description: "Gold Price",
    categoryType: "global",
  },
  {
    id: "sugar_global",
    name: "Global Sugar Price",
    source: "dbnomics",
    datasetCode: "PSUGA_USD",
    providerCode: "IMF",
    unit: "USD per pound",
    category: "commodities",
    description: "Sugar, Global Price",
    categoryType: "global",
  },
  {
    id: "natural_gas",
    name: "Natural Gas Price",
    source: "dbnomics",
    datasetCode: "DHHNGSP",
    providerCode: "FRED",
    unit: "Dollars per Million BTU",
    category: "commodities",
    description: "Henry Hub Natural Gas Spot Price",
    categoryType: "global",
  },

  // ─── India ─────────────────────────────────────────────────────────────────
  {
    id: "in_gdp",
    name: "GDP",
    source: "fred",
    seriesId: "MKTGDPIA646NWDB",
    unit: "Current US Dollars",
    category: "nationalAccounts",
    description: "Gross Domestic Product for India",
    categoryType: "country",
    country: "India",
  },
  {
    id: "in_cpi",
    name: "CPI",
    source: "fred",
    seriesId: "CPALTT01INM659N",
    unit: "Index 2015=100",
    category: "prices",
    description: "Consumer Price Indices: Total for India",
    categoryType: "country",
    country: "India",
  },
  {
    id: "in_interest_rate",
    name: "Interest Rate",
    source: "fred",
    seriesId: "INTDSRINM193N",
    unit: "Percent per Annum",
    category: "interestRates",
    description: "Interest Rates, Discount Rate for India",
    categoryType: "country",
    country: "India",
  },

  // ─── Brazil ────────────────────────────────────────────────────────────────
  {
    id: "br_gdp",
    name: "GDP",
    source: "fred",
    seriesId: "MKTGDPBRA646NWDB",
    unit: "Current US Dollars",
    category: "nationalAccounts",
    description: "Gross Domestic Product for Brazil",
    categoryType: "country",
    country: "Brazil",
  },
  {
    id: "br_cpi",
    name: "CPI",
    source: "fred",
    seriesId: "CPALTT01BRM659N",
    unit: "Index 2015=100",
    category: "prices",
    description: "Consumer Price Indices: Total for Brazil",
    categoryType: "country",
    country: "Brazil",
  },
  {
    id: "br_interest_rate",
    name: "Interest Rate",
    source: "fred",
    seriesId: "INTDSRBRM193N",
    unit: "Percent per Annum",
    category: "interestRates",
    description: "Interest Rates, Discount Rate for Brazil",
    categoryType: "country",
    country: "Brazil",
  },

  // ─── South Korea ───────────────────────────────────────────────────────────
  {
    id: "kr_gdp",
    name: "GDP",
    source: "fred",
    seriesId: "MKTGDPKR646NWDB",
    unit: "Current US Dollars",
    category: "nationalAccounts",
    description: "Gross Domestic Product for South Korea",
    categoryType: "country",
    country: "SouthKorea",
  },
  {
    id: "kr_cpi",
    name: "CPI",
    source: "fred",
    seriesId: "CPALTT01KRM659N",
    unit: "Index 2015=100",
    category: "prices",
    description: "Consumer Price Indices: Total for South Korea",
    categoryType: "country",
    country: "SouthKorea",
  },
  {
    id: "kr_interest_rate",
    name: "Interest Rate",
    source: "fred",
    seriesId: "INTDSRKR193N",
    unit: "Percent per Annum",
    category: "interestRates",
    description: "Interest Rates, Discount Rate for South Korea",
    categoryType: "country",
    country: "SouthKorea",
  },

  // ─── Canada ────────────────────────────────────────────────────────────────
  {
    id: "ca_gdp",
    name: "GDP",
    source: "fred",
    seriesId: "NGDPRDPCNADGP",
    unit: "Current US Dollars",
    category: "nationalAccounts",
    description: "Gross Domestic Product for Canada",
    categoryType: "country",
    country: "Canada",
  },
  {
    id: "ca_unemployment",
    name: "Unemployment Rate",
    source: "fred",
    seriesId: "LRHUTTTTCAM156S",
    unit: "Percent",
    category: "labor",
    description: "Monthly Unemployment Rate for Canada",
    categoryType: "country",
    country: "Canada",
  },
  {
    id: "ca_cpi",
    name: "CPI",
    source: "fred",
    seriesId: "CPALTT01CAM659N",
    unit: "Index 2015=100",
    category: "prices",
    description: "Consumer Price Indices: Total for Canada",
    categoryType: "country",
    country: "Canada",
  },
  {
    id: "ca_interest_rate",
    name: "Interest Rate",
    source: "fred",
    seriesId: "INTDSRCAM193N",
    unit: "Percent per Annum",
    category: "interestRates",
    description: "Interest Rates, Discount Rate for Canada",
    categoryType: "country",
    country: "Canada",
  },

  // ─── Australia ─────────────────────────────────────────────────────────────
  {
    id: "au_gdp",
    name: "GDP",
    source: "fred",
    seriesId: "MKTGDPAU646NWDB",
    unit: "Current US Dollars",
    category: "nationalAccounts",
    description: "Gross Domestic Product for Australia",
    categoryType: "country",
    country: "Australia",
  },
  {
    id: "au_unemployment",
    name: "Unemployment Rate",
    source: "fred",
    seriesId: "LRHUTTTTAIM156S",
    unit: "Percent",
    category: "labor",
    description: "Monthly Unemployment Rate for Australia",
    categoryType: "country",
    country: "Australia",
  },
  {
    id: "au_cpi",
    name: "CPI",
    source: "fred",
    seriesId: "CPALTT01AIM659N",
    unit: "Index 2015=100",
    category: "prices",
    description: "Consumer Price Indices: Total for Australia",
    categoryType: "country",
    country: "Australia",
  },
  {
    id: "au_interest_rate",
    name: "Interest Rate",
    source: "fred",
    seriesId: "INTDSRAIM193N",
    unit: "Percent per Annum",
    category: "interestRates",
    description: "Interest Rates, Discount Rate for Australia",
    categoryType: "country",
    country: "Australia",
  },

  // ─── Recession Risk / Forecast ─────────────────────────────────────────────
  {
    id: "yield_curve_10y2y",
    name: "Yield Curve (10Y-2Y)",
    source: "fred",
    seriesId: "T10Y2Y",
    unit: "Percent",
    category: "recessionRisk",
    description:
      "10-Year Treasury Constant Maturity Minus 2-Year; negative values historically signal recession",
    categoryType: "global",
  },
  {
    id: "yield_curve_10y3m",
    name: "Yield Curve (10Y-3M)",
    source: "fred",
    seriesId: "T10Y3M",
    unit: "Percent",
    category: "recessionRisk",
    description:
      "10-Year Treasury Constant Maturity Minus 3-Month; negative values historically signal recession",
    categoryType: "global",
  },
  {
    id: "leading_index",
    name: "Leading Economic Index",
    source: "fred",
    seriesId: "USSLIND",
    unit: "Index 2016=100",
    category: "recessionRisk",
    description:
      "Conference Board Leading Economic Index for the United States",
    categoryType: "global",
  },
];
