import type { Indicator } from "@/types";

export const indicators: Indicator[] = [
  // ─── United States ─────────────────────────────────────────────────────────
  {
    id: "gdp",
    name: "GDP",
    source: "fred",
    seriesId: "GDP",
    unit: "Dollars",
    category: "nationalAccounts",
    description: "Gross Domestic Product",
    categoryType: "country",
    country: "US",
  },
  {
    id: "unemployment",
    name: "Unemployment Rate",
    source: "fred",
    seriesId: "UNRATE",
    unit: "Percent",
    category: "labor",
    description: "Civilian Unemployment Rate",
    categoryType: "country",
    country: "US",
  },
  {
    id: "cpi",
    name: "CPI",
    source: "fred",
    seriesId: "CPIAUCSL",
    unit: "Index 1982-1984=100",
    category: "prices",
    description: "Consumer Price Index for All Urban Consumers",
    categoryType: "country",
    country: "US",
  },
  {
    id: "fed_funds_rate",
    name: "Federal Funds Rate",
    source: "fred",
    seriesId: "FEDFUNDS",
    unit: "Percent",
    category: "interestRates",
    description: "Federal Funds Effective Rate",
    categoryType: "country",
    country: "US",
  },
  {
    id: "treasury_10y",
    name: "10-Year Treasury Rate",
    source: "fred",
    seriesId: "DGS10",
    unit: "Percent",
    category: "interestRates",
    description:
      "Market Yield on U.S. Treasury Securities at 10-Year Constant Maturity",
    categoryType: "country",
    country: "US",
  },
  {
    id: "sp500",
    name: "S&P 500",
    source: "fred",
    seriesId: "SP500",
    unit: "Index",
    category: "stockMarket",
    description: "S&P 500 Index",
    categoryType: "country",
    country: "US",
  },
  {
    id: "industrial_production",
    name: "Industrial Production",
    source: "fred",
    seriesId: "INDPRO",
    unit: "Index 2017=100",
    category: "production",
    description: "Industrial Production: Total Index",
    categoryType: "country",
    country: "US",
  },
  {
    id: "housing_starts",
    name: "Housing Starts",
    source: "fred",
    seriesId: "HOUST",
    unit: "Thousands of Units",
    category: "housing",
    description: "New Privately-Owned Housing Units Started",
    categoryType: "country",
    country: "US",
  },
  {
    id: "consumer_sentiment",
    name: "Consumer Sentiment",
    source: "fred",
    seriesId: "UMCSENT",
    unit: "Index 1966Q1=100",
    category: "sentiment",
    description: "University of Michigan: Consumer Sentiment",
    categoryType: "country",
    country: "US",
  },
  {
    id: "pce",
    name: "PCE",
    source: "fred",
    seriesId: "PCE",
    unit: "Dollars",
    category: "nationalAccounts",
    description: "Personal Consumption Expenditures",
    categoryType: "country",
    country: "US",
  },
  {
    id: "trade_balance",
    name: "Trade Balance",
    source: "fred",
    seriesId: "BOPGSTB",
    unit: "Dollars",
    category: "trade",
    description:
      "Trade Balance: Goods and Services, Balance of Payments Basis",
    categoryType: "country",
    country: "US",
  },
  {
    id: "retail_sales",
    name: "Retail Sales",
    source: "fred",
    seriesId: "RSAFS",
    unit: "Dollars",
    category: "consumption",
    description: "Advance Retail Sales: Retail Trade",
    categoryType: "country",
    country: "US",
  },

  // ─── Euro Area ─────────────────────────────────────────────────────────────
  {
    id: "eu_gdp",
    name: "GDP",
    source: "fred",
    seriesId: "CLVMNACSCAB1GQEA19",
    unit: "Euros",
    category: "nationalAccounts",
    description: "Real Gross Domestic Product for Euro Area (19 Countries)",
    categoryType: "country",
    country: "EuroArea",
    currency: "EUR",
    exchangeRateSeriesId: "DEXUSEU",
  },
  {
    id: "eu_unemployment",
    name: "Unemployment Rate",
    source: "fred",
    seriesId: "LRHUTTTTEZM156S",
    unit: "Percent",
    category: "labor",
    description:
      "Harmonised Unemployment Rate: Total: All Persons for Euro Area",
    categoryType: "country",
    country: "EuroArea",
  },
  {
    id: "eu_hicp",
    name: "HICP",
    source: "fred",
    seriesId: "CP0000EZ19M086NEST",
    unit: "Index 2025=100",
    category: "prices",
    description:
      "Harmonized Index of Consumer Prices: Total for Euro Area (19 Countries)",
    categoryType: "country",
    country: "EuroArea",
  },
  {
    id: "eu_ecb_rate",
    name: "ECB Main Refinancing Rate",
    source: "fred",
    seriesId: "ECBMRRFR",
    unit: "Percent",
    category: "interestRates",
    description:
      "ECB Main Refinancing Operations Rate: Fixed Rate Tenders for Euro Area",
    categoryType: "country",
    country: "EuroArea",
  },

  // ─── Japan ─────────────────────────────────────────────────────────────────
  {
    id: "jp_gdp",
    name: "GDP",
    source: "fred",
    seriesId: "JPNRGDPEXP",
    unit: "Yen",
    category: "nationalAccounts",
    description: "Real Gross Domestic Product for Japan",
    categoryType: "country",
    country: "Japan",
    currency: "JPY",
    exchangeRateSeriesId: "DEXJPUS",
  },
  {
    id: "jp_unemployment",
    name: "Unemployment Rate",
    source: "fred",
    seriesId: "LRHUTTTTJPM156S",
    unit: "Percent",
    category: "labor",
    description:
      "Infra-Annual Labor Statistics: Monthly Unemployment Rate Total for Japan",
    categoryType: "country",
    country: "Japan",
  },
  {
    id: "jp_cpi",
    name: "CPI",
    source: "fred",
    seriesId: "JPNCPIALLMINMEI",
    unit: "Index 2015=100",
    category: "prices",
    description: "Consumer Price Index: Total for Japan",
    categoryType: "country",
    country: "Japan",
  },
  {
    id: "jp_boj_rate",
    name: "BOJ Policy Rate",
    source: "fred",
    seriesId: "IRSTCI01JPM156N",
    unit: "Percent",
    category: "interestRates",
    description: "Call Money/Interbank Rate for Japan",
    categoryType: "country",
    country: "Japan",
  },

  // ─── China ─────────────────────────────────────────────────────────────────
  {
    id: "cn_gdp",
    name: "GDP",
    source: "fred",
    seriesId: "MKTGDPCNA646NWDB",
    unit: "Current US Dollars",
    category: "nationalAccounts",
    description: "Gross Domestic Product for China",
    categoryType: "country",
    country: "China",
  },
  {
    id: "cn_cpi",
    name: "CPI",
    source: "fred",
    seriesId: "CPALTT01CNM659N",
    unit: "Index 2015=100",
    category: "prices",
    description: "Consumer Price Indices: Total for China",
    categoryType: "country",
    country: "China",
  },
  {
    id: "cn_interest_rate",
    name: "Interest Rate",
    source: "fred",
    seriesId: "INTDSRCNM193N",
    unit: "Percent per Annum",
    category: "interestRates",
    description: "Interest Rates, Discount Rate for China",
    categoryType: "country",
    country: "China",
  },

  // ─── United Kingdom ────────────────────────────────────────────────────────
  {
    id: "uk_gdp",
    name: "GDP",
    source: "fred",
    seriesId: "UKNGDP",
    unit: "Pounds",
    category: "nationalAccounts",
    description: "Gross Domestic Product for United Kingdom",
    categoryType: "country",
    country: "UK",
    currency: "GBP",
    exchangeRateSeriesId: "DEXUSUK",
  },
  {
    id: "uk_unemployment",
    name: "Unemployment Rate",
    source: "fred",
    seriesId: "LRHUTTTTGBM156S",
    unit: "Percent",
    category: "labor",
    description:
      "Infra-Annual Labor Statistics: Monthly Unemployment Rate Total for United Kingdom",
    categoryType: "country",
    country: "UK",
  },
  {
    id: "uk_cpi",
    name: "CPI",
    source: "fred",
    seriesId: "GBRCPIALLMINMEI",
    unit: "Index 2015=100",
    category: "prices",
    description: "Consumer Price Indices: CPI Total for United Kingdom",
    categoryType: "country",
    country: "UK",
  },
  {
    id: "uk_boe_rate",
    name: "BOE Bank Rate",
    source: "fred",
    seriesId: "BOERUKM",
    unit: "Percent per Annum",
    category: "interestRates",
    description: "Bank of England Policy Rate",
    categoryType: "country",
    country: "UK",
  },

  // ─── Global / Commodities ──────────────────────────────────────────────────
  {
    id: "oil_wti",
    name: "WTI Crude Oil",
    source: "fred",
    seriesId: "DCOILWTICO",
    unit: "Dollars per Barrel",
    category: "commodities",
    description: "Crude Oil WTI Spot Price",
    categoryType: "global",
  },
  {
    id: "gold_price",
    name: "Gold Price",
    source: "fred",
    seriesId: "GOLDAMGBD228NLBM",
    unit: "US Dollars per Troy Ounce",
    category: "commodities",
    description: "Gold Fixing Price",
    categoryType: "global",
  },
  {
    id: "sugar_global",
    name: "Global Sugar Price",
    source: "fred",
    seriesId: "PSUGA_USD",
    unit: "US Cents per Pound",
    category: "commodities",
    description: "Global Sugar Price (Daily)",
    categoryType: "global",
  },
  {
    id: "natural_gas",
    name: "Natural Gas Price",
    source: "fred",
    seriesId: "DHHNGSP",
    unit: "Dollars per Million BTU",
    category: "commodities",
    description: "Henry Hub Natural Gas Spot Price",
    categoryType: "global",
  },

  // ─── India ─────────────────────────────────────────────────────────────────
  {
    id: "in_gdp",
    name: "GDP",
    source: "fred",
    seriesId: "MKTGDPINA646NWDB",
    unit: "Current US Dollars",
    category: "nationalAccounts",
    description: "Gross Domestic Product for India",
    categoryType: "country",
    country: "India",
  },
  {
    id: "in_cpi",
    name: "CPI",
    source: "fred",
    seriesId: "CPALTT01INM659N",
    unit: "Index 2015=100",
    category: "prices",
    description: "Consumer Price Indices: Total for India",
    categoryType: "country",
    country: "India",
  },
  {
    id: "in_interest_rate",
    name: "Interest Rate",
    source: "fred",
    seriesId: "INTDSRINM193N",
    unit: "Percent per Annum",
    category: "interestRates",
    description: "Interest Rates, Discount Rate for India",
    categoryType: "country",
    country: "India",
  },

  // ─── Brazil ────────────────────────────────────────────────────────────────
  {
    id: "br_gdp",
    name: "GDP",
    source: "fred",
    seriesId: "MKTGDPBRA646NWDB",
    unit: "Current US Dollars",
    category: "nationalAccounts",
    description: "Gross Domestic Product for Brazil",
    categoryType: "country",
    country: "Brazil",
  },
  {
    id: "br_cpi",
    name: "CPI",
    source: "fred",
    seriesId: "CPALTT01BRM659N",
    unit: "Index 2015=100",
    category: "prices",
    description: "Consumer Price Indices: Total for Brazil",
    categoryType: "country",
    country: "Brazil",
  },
  {
    id: "br_interest_rate",
    name: "Interest Rate",
    source: "fred",
    seriesId: "INTDSRBRM193N",
    unit: "Percent per Annum",
    category: "interestRates",
    description: "Interest Rates, Discount Rate for Brazil",
    categoryType: "country",
    country: "Brazil",
  },

  // ─── South Korea ───────────────────────────────────────────────────────────
  {
    id: "kr_gdp",
    name: "GDP",
    source: "fred",
    seriesId: "MKTGDPKRA646NWDB",
    unit: "Current US Dollars",
    category: "nationalAccounts",
    description: "Gross Domestic Product for South Korea",
    categoryType: "country",
    country: "SouthKorea",
  },
  {
    id: "kr_cpi",
    name: "CPI",
    source: "fred",
    seriesId: "CPALTT01KRM659N",
    unit: "Index 2015=100",
    category: "prices",
    description: "Consumer Price Indices: Total for South Korea",
    categoryType: "country",
    country: "SouthKorea",
  },
  {
    id: "kr_interest_rate",
    name: "Interest Rate",
    source: "fred",
    seriesId: "INTDSRKRM193N",
    unit: "Percent per Annum",
    category: "interestRates",
    description: "Interest Rates, Discount Rate for South Korea",
    categoryType: "country",
    country: "SouthKorea",
  },

  // ─── Canada ────────────────────────────────────────────────────────────────
  {
    id: "ca_gdp",
    name: "GDP",
    source: "fred",
    seriesId: "MKTGDPCAA646NWDB",
    unit: "Current US Dollars",
    category: "nationalAccounts",
    description: "Gross Domestic Product for Canada",
    categoryType: "country",
    country: "Canada",
  },
  {
    id: "ca_unemployment",
    name: "Unemployment Rate",
    source: "fred",
    seriesId: "LRHUTTTTCAM156S",
    unit: "Percent",
    category: "labor",
    description: "Monthly Unemployment Rate for Canada",
    categoryType: "country",
    country: "Canada",
  },
  {
    id: "ca_cpi",
    name: "CPI",
    source: "fred",
    seriesId: "CPALTT01CAM659N",
    unit: "Index 2015=100",
    category: "prices",
    description: "Consumer Price Indices: Total for Canada",
    categoryType: "country",
    country: "Canada",
  },
  {
    id: "ca_interest_rate",
    name: "Interest Rate",
    source: "fred",
    seriesId: "INTDSRCAM193N",
    unit: "Percent per Annum",
    category: "interestRates",
    description: "Interest Rates, Discount Rate for Canada",
    categoryType: "country",
    country: "Canada",
  },

  // ─── Australia ─────────────────────────────────────────────────────────────
  {
    id: "au_gdp",
    name: "GDP",
    source: "fred",
    seriesId: "NGDPRSAXDCAUQ",
    unit: "Domestic Currency",
    category: "nationalAccounts",
    description: "Real Gross Domestic Product for Australia",
    categoryType: "country",
    country: "Australia",
    currency: "AUD",
    exchangeRateSeriesId: "DEXUSAL",
  },
  {
    id: "au_unemployment",
    name: "Unemployment Rate",
    source: "fred",
    seriesId: "LRUNTTTTAUQ156S",
    unit: "Percent",
    category: "labor",
    description: "Monthly Unemployment Rate for Australia",
    categoryType: "country",
    country: "Australia",
  },
  {
    id: "au_cpi",
    name: "CPI",
    source: "fred",
    seriesId: "CPALTT01AUQ659N",
    unit: "Index 2015=100",
    category: "prices",
    description: "Consumer Price Indices: Total for Australia",
    categoryType: "country",
    country: "Australia",
  },
  {
    id: "au_interest_rate",
    name: "Interest Rate",
    source: "fred",
    seriesId: "IRSTCI01AUM156N",
    unit: "Percent",
    category: "interestRates",
    description: "Call Money/Interbank Rate for Australia",
    categoryType: "country",
    country: "Australia",
  },

  // ─── Recession Risk / Forecast ─────────────────────────────────────────────
  {
    id: "yield_curve_10y2y",
    name: "Yield Curve (10Y-2Y)",
    source: "fred",
    seriesId: "T10Y2Y",
    unit: "Percent",
    category: "recessionRisk",
    description:
      "10-Year Treasury Constant Maturity Minus 2-Year; negative values historically signal recession",
    categoryType: "global",
  },
  {
    id: "yield_curve_10y3m",
    name: "Yield Curve (10Y-3M)",
    source: "fred",
    seriesId: "T10Y3M",
    unit: "Percent",
    category: "recessionRisk",
    description:
      "10-Year Treasury Constant Maturity Minus 3-Month; negative values historically signal recession",
    categoryType: "global",
  },
  {
    id: "leading_index",
    name: "Leading Economic Index",
    source: "fred",
    seriesId: "USSLIND",
    unit: "Index 2016=100",
    category: "recessionRisk",
    description:
      "Conference Board Leading Economic Index for the United States",
    categoryType: "global",
  },
  // ─── World Bank ────────────────────────────────────────────────────────────
  // All indicators use country-specific World Bank data via countryCode
  // GDP: NY.GDP.MKTP.CD (current US$)
  // Population: SP.POP.TOTL
  // GDP per capita: NY.GDP.PCAP.CD
  // GDP growth: NY.GDP.MKTP.KD.ZG (annual %)
  // Inflation: FP.CPI.TOTL.ZG (GDP deflator annual %)
  // Government debt: GC.DOD.TOTL.GD.ZS (% of GDP)
  // Exports: NE.EXP.GNFS.CD (goods & services, current US$)
  // Imports: NE.IMP.GNFS.CD (goods & services, current US$)
  // Tertiary enrollment: SL.IMM.TETL (% of relevant age group)

  // ── United States ──
  {
    id: "worldbank_gdp_us",
    name: "GDP (World Bank)",
    source: "worldbank",
    seriesId: "NY.GDP.MKTP.CD",
    unit: "Current US Dollars",
    category: "nationalAccounts",
    description: "GDP at current US dollars from World Bank",
    categoryType: "country",
    country: "US",
    countryCode: "US",
  },
  {
    id: "worldbank_sp_pop_us",
    name: "Population (World Bank)",
    source: "worldbank",
    seriesId: "SP.POP.TOTL",
    unit: "People",
    category: "demographics",
    description: "Total population from World Bank",
    categoryType: "country",
    country: "US",
    countryCode: "US",
  },
  {
    id: "worldbank_gdp_per_capita_us",
    name: "GDP per Capita (World Bank)",
    source: "worldbank",
    seriesId: "NY.GDP.PCAP.CD",
    unit: "US Dollars",
    category: "nationalAccounts",
    description: "GDP per capita from World Bank",
    categoryType: "country",
    country: "US",
    countryCode: "US",
  },
  {
    id: "worldbank_gdp_growth_us",
    name: "GDP Growth (World Bank)",
    source: "worldbank",
    seriesId: "NY.GDP.MKTP.KD.ZG",
    unit: "Percent",
    category: "nationalAccounts",
    description: "Annual GDP growth rate from World Bank",
    categoryType: "country",
    country: "US",
    countryCode: "US",
  },
  {
    id: "worldbank_inflation_us",
    name: "Inflation (World Bank)",
    source: "worldbank",
    seriesId: "FP.CPI.TOTL.ZG",
    unit: "Percent",
    category: "prices",
    description: "Inflation, GDP deflator (annual %) from World Bank",
    categoryType: "country",
    country: "US",
    countryCode: "US",
  },
  {
    id: "worldbank_government_debt_us",
    name: "Govt Debt (World Bank)",
    source: "worldbank",
    seriesId: "GC.DOD.TOTL.GD.ZS",
    unit: "% of GDP",
    category: "government",
    description: "Gross domestic debt from World Bank",
    categoryType: "country",
    country: "US",
    countryCode: "US",
  },
  {
    id: "worldbank_exports_us",
    name: "Exports (World Bank)",
    source: "worldbank",
    seriesId: "NE.EXP.GNFS.CD",
    unit: "Current US Dollars",
    category: "trade",
    description: "Exports of goods and services from World Bank",
    categoryType: "country",
    country: "US",
    countryCode: "US",
  },
  {
    id: "worldbank_imports_us",
    name: "Imports (World Bank)",
    source: "worldbank",
    seriesId: "NE.IMP.GNFS.CD",
    unit: "Current US Dollars",
    category: "trade",
    description: "Imports of goods and services from World Bank",
    categoryType: "country",
    country: "US",
    countryCode: "US",
  },

  // ── Euro Area ──
  {
    id: "worldbank_gdp_eu",
    name: "GDP (World Bank)",
    source: "worldbank",
    seriesId: "NY.GDP.MKTP.CD",
    unit: "Current US Dollars",
    category: "nationalAccounts",
    description: "GDP at current US dollars from World Bank",
    categoryType: "country",
    country: "EuroArea",
    countryCode: "EU",
  },
  {
    id: "worldbank_gdp_growth_eu",
    name: "GDP Growth (World Bank)",
    source: "worldbank",
    seriesId: "NY.GDP.MKTP.KD.ZG",
    unit: "Percent",
    category: "nationalAccounts",
    description: "Annual GDP growth rate from World Bank",
    categoryType: "country",
    country: "EuroArea",
    countryCode: "EU",
  },
  {
    id: "worldbank_inflation_eu",
    name: "Inflation (World Bank)",
    source: "worldbank",
    seriesId: "FP.CPI.TOTL.ZG",
    unit: "Percent",
    category: "prices",
    description: "Inflation, GDP deflator (annual %) from World Bank",
    categoryType: "country",
    country: "EuroArea",
    countryCode: "EU",
  },

  // ── Japan ──
  {
    id: "worldbank_gdp_jp",
    name: "GDP (World Bank)",
    source: "worldbank",
    seriesId: "NY.GDP.MKTP.CD",
    unit: "Current US Dollars",
    category: "nationalAccounts",
    description: "GDP at current US dollars from World Bank",
    categoryType: "country",
    country: "Japan",
    countryCode: "JP",
  },
  {
    id: "worldbank_gdp_growth_jp",
    name: "GDP Growth (World Bank)",
    source: "worldbank",
    seriesId: "NY.GDP.MKTP.KD.ZG",
    unit: "Percent",
    category: "nationalAccounts",
    description: "Annual GDP growth rate from World Bank",
    categoryType: "country",
    country: "Japan",
    countryCode: "JP",
  },
  {
    id: "worldbank_inflation_jp",
    name: "Inflation (World Bank)",
    source: "worldbank",
    seriesId: "FP.CPI.TOTL.ZG",
    unit: "Percent",
    category: "prices",
    description: "Inflation, GDP deflator (annual %) from World Bank",
    categoryType: "country",
    country: "Japan",
    countryCode: "JP",
  },

  // ── China ──
  {
    id: "worldbank_gdp_cn",
    name: "GDP (World Bank)",
    source: "worldbank",
    seriesId: "NY.GDP.MKTP.CD",
    unit: "Current US Dollars",
    category: "nationalAccounts",
    description: "GDP at current US dollars from World Bank",
    categoryType: "country",
    country: "China",
    countryCode: "CN",
  },
  {
    id: "worldbank_gdp_growth_cn",
    name: "GDP Growth (World Bank)",
    source: "worldbank",
    seriesId: "NY.GDP.MKTP.KD.ZG",
    unit: "Percent",
    category: "nationalAccounts",
    description: "Annual GDP growth rate from World Bank",
    categoryType: "country",
    country: "China",
    countryCode: "CN",
  },
  {
    id: "worldbank_inflation_cn",
    name: "Inflation (World Bank)",
    source: "worldbank",
    seriesId: "FP.CPI.TOTL.ZG",
    unit: "Percent",
    category: "prices",
    description: "Inflation, GDP deflator (annual %) from World Bank",
    categoryType: "country",
    country: "China",
    countryCode: "CN",
  },

  // ── United Kingdom ──
  {
    id: "worldbank_gdp_gb",
    name: "GDP (World Bank)",
    source: "worldbank",
    seriesId: "NY.GDP.MKTP.CD",
    unit: "Current US Dollars",
    category: "nationalAccounts",
    description: "GDP at current US dollars from World Bank",
    categoryType: "country",
    country: "UK",
    countryCode: "GB",
  },
  {
    id: "worldbank_gdp_growth_gb",
    name: "GDP Growth (World Bank)",
    source: "worldbank",
    seriesId: "NY.GDP.MKTP.KD.ZG",
    unit: "Percent",
    category: "nationalAccounts",
    description: "Annual GDP growth rate from World Bank",
    categoryType: "country",
    country: "UK",
    countryCode: "GB",
  },
  {
    id: "worldbank_inflation_gb",
    name: "Inflation (World Bank)",
    source: "worldbank",
    seriesId: "FP.CPI.TOTL.ZG",
    unit: "Percent",
    category: "prices",
    description: "Inflation, GDP deflator (annual %) from World Bank",
    categoryType: "country",
    country: "UK",
    countryCode: "GB",
  },

  // ── India ──
  {
    id: "worldbank_gdp_in",
    name: "GDP (World Bank)",
    source: "worldbank",
    seriesId: "NY.GDP.MKTP.CD",
    unit: "Current US Dollars",
    category: "nationalAccounts",
    description: "GDP at current US dollars from World Bank",
    categoryType: "country",
    country: "India",
    countryCode: "IN",
  },
  {
    id: "worldbank_gdp_growth_in",
    name: "GDP Growth (World Bank)",
    source: "worldbank",
    seriesId: "NY.GDP.MKTP.KD.ZG",
    unit: "Percent",
    category: "nationalAccounts",
    description: "Annual GDP growth rate from World Bank",
    categoryType: "country",
    country: "India",
    countryCode: "IN",
  },
  {
    id: "worldbank_inflation_in",
    name: "Inflation (World Bank)",
    source: "worldbank",
    seriesId: "FP.CPI.TOTL.ZG",
    unit: "Percent",
    category: "prices",
    description: "Inflation, GDP deflator (annual %) from World Bank",
    categoryType: "country",
    country: "India",
    countryCode: "IN",
  },

  // ── Brazil ──
  {
    id: "worldbank_gdp_br",
    name: "GDP (World Bank)",
    source: "worldbank",
    seriesId: "NY.GDP.MKTP.CD",
    unit: "Current US Dollars",
    category: "nationalAccounts",
    description: "GDP at current US dollars from World Bank",
    categoryType: "country",
    country: "Brazil",
    countryCode: "BR",
  },
  {
    id: "worldbank_gdp_growth_br",
    name: "GDP Growth (World Bank)",
    source: "worldbank",
    seriesId: "NY.GDP.MKTP.KD.ZG",
    unit: "Percent",
    category: "nationalAccounts",
    description: "Annual GDP growth rate from World Bank",
    categoryType: "country",
    country: "Brazil",
    countryCode: "BR",
  },
  {
    id: "worldbank_inflation_br",
    name: "Inflation (World Bank)",
    source: "worldbank",
    seriesId: "FP.CPI.TOTL.ZG",
    unit: "Percent",
    category: "prices",
    description: "Inflation, GDP deflator (annual %) from World Bank",
    categoryType: "country",
    country: "Brazil",
    countryCode: "BR",
  },

  // ── South Korea ──
  {
    id: "worldbank_gdp_kr",
    name: "GDP (World Bank)",
    source: "worldbank",
    seriesId: "NY.GDP.MKTP.CD",
    unit: "Current US Dollars",
    category: "nationalAccounts",
    description: "GDP at current US dollars from World Bank",
    categoryType: "country",
    country: "SouthKorea",
    countryCode: "KR",
  },
  {
    id: "worldbank_gdp_growth_kr",
    name: "GDP Growth (World Bank)",
    source: "worldbank",
    seriesId: "NY.GDP.MKTP.KD.ZG",
    unit: "Percent",
    category: "nationalAccounts",
    description: "Annual GDP growth rate from World Bank",
    categoryType: "country",
    country: "SouthKorea",
    countryCode: "KR",
  },
  {
    id: "worldbank_inflation_kr",
    name: "Inflation (World Bank)",
    source: "worldbank",
    seriesId: "FP.CPI.TOTL.ZG",
    unit: "Percent",
    category: "prices",
    description: "Inflation, GDP deflator (annual %) from World Bank",
    categoryType: "country",
    country: "SouthKorea",
    countryCode: "KR",
  },

  // ── Canada ──
  {
    id: "worldbank_gdp_ca",
    name: "GDP (World Bank)",
    source: "worldbank",
    seriesId: "NY.GDP.MKTP.CD",
    unit: "Current US Dollars",
    category: "nationalAccounts",
    description: "GDP at current US dollars from World Bank",
    categoryType: "country",
    country: "Canada",
    countryCode: "CA",
  },
  {
    id: "worldbank_gdp_growth_ca",
    name: "GDP Growth (World Bank)",
    source: "worldbank",
    seriesId: "NY.GDP.MKTP.KD.ZG",
    unit: "Percent",
    category: "nationalAccounts",
    description: "Annual GDP growth rate from World Bank",
    categoryType: "country",
    country: "Canada",
    countryCode: "CA",
  },
  {
    id: "worldbank_inflation_ca",
    name: "Inflation (World Bank)",
    source: "worldbank",
    seriesId: "FP.CPI.TOTL.ZG",
    unit: "Percent",
    category: "prices",
    description: "Inflation, GDP deflator (annual %) from World Bank",
    categoryType: "country",
    country: "Canada",
    countryCode: "CA",
  },

  // ── Australia ──
  {
    id: "worldbank_gdp_au",
    name: "GDP (World Bank)",
    source: "worldbank",
    seriesId: "NY.GDP.MKTP.CD",
    unit: "Current US Dollars",
    category: "nationalAccounts",
    description: "GDP at current US dollars from World Bank",
    categoryType: "country",
    country: "Australia",
    countryCode: "AU",
  },
  {
    id: "worldbank_gdp_growth_au",
    name: "GDP Growth (World Bank)",
    source: "worldbank",
    seriesId: "NY.GDP.MKTP.KD.ZG",
    unit: "Percent",
    category: "nationalAccounts",
    description: "Annual GDP growth rate from World Bank",
    categoryType: "country",
    country: "Australia",
    countryCode: "AU",
  },
  {
    id: "worldbank_inflation_au",
    name: "Inflation (World Bank)",
    source: "worldbank",
    seriesId: "FP.CPI.TOTL.ZG",
    unit: "Percent",
    category: "prices",
    description: "Inflation, GDP deflator (annual %) from World Bank",
    categoryType: "country",
    country: "Australia",
    countryCode: "AU",
  },
];
